name: demo
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  json_annotation: ^2.0.0
  # State
  provider: ^3.1.0

  # Base Component
  # WebView iOS添加键值对 o.flutter.embedded_views_preview = YES 
  flutter_webview_plugin: ^0.3.8
  device_info: ^0.4.0+1
  package_info: ^0.4.0+6
  quiver: ^2.0.5
  #  connectivity: ^0.4.3+6

  # Data
  #  json_annotation: ^2.4.0
  dio: ^3.0.1
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.0
  shared_preferences: ^0.5.3+5
  # 本地json对象存储
  localstorage: ^2.0.0

  # Html Encoder/Decoder
  html_unescape: ^1.0.1+3
  # 解析html标签
  flutter_html: ^0.10.4

  # 判断list是否相等
  collection: ^1.14.11
  #  crypto: ^2.0.6

  # UI
  oktoast: ^2.1.7
  pull_to_refresh: ^1.5.6
  flutter_swiper: ^1.1.6
  cached_network_image: ^1.1.1
  # 类iOS侧滑菜单
  flutter_slidable: 0.5.3
  # 谁用谁闪亮
  shimmer: ^1.0.0
  # 识别图片的主要颜色
  #  palette_generator: ^0.2.0
  # 更新展示支持mark_down
  flutter_markdown: ^0.2.0
  flare_flutter: ^1.5.9

  # third_app
  url_launcher: ^5.1.6 #启动第三方app
  share: 0.6.2+1 #分享
  launch_review: ^2.0.0
  open_file: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - images/